import 'package:flutter/material.dart';

class AsyncFAB extends FloatingActionButton {
  const AsyncFAB({
    Key? key,
    required VoidCallback? onPressed,
    MouseCursor? mouseCursor,
    bool mini = false,
    ShapeBorder? shape,
    Clip clipBehavior = Clip.none,
    Color? focusColor,
    Color? hoverColor,
    Color? splashColor,
    double? disabledElevation,
    double? focusElevation,
    double? hoverElevation,
    double? highlightElevation,
    bool autofocus = false,
    MaterialTapTargetSize? materialTapTargetSize,
    bool? enableFeedback,
    String? tooltip,
    Color? foregroundColor,
    Color? backgroundColor,
    double? elevation,
    FocusNode? focusNode,
    String? heroTag,
    bool isExtended = false,
    required Widget child,
  }) : super(
          key: key,
          onPressed: onPressed,
          mouseCursor: mouseCursor,
          mini: mini,
          shape: shape,
          clipBehavior: clipBehavior,
          focusColor: focusColor,
          hoverColor: hoverColor,
          splashColor: splashColor,
          disabledElevation: disabledElevation,
          focusElevation: focusElevation,
          hoverElevation: hoverElevation,
          highlightElevation: highlightElevation,
          autofocus: autofocus,
          materialTapTargetSize: materialTapTargetSize,
          enableFeedback: enableFeedback,
          tooltip: tooltip,
          foregroundColor: foregroundColor,
          backgroundColor: backgroundColor,
          child: child,
          elevation: elevation,
          focusNode: focusNode,
          heroTag: heroTag,
          isExtended: isExtended,
        );

  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(
      key: key,
      onPressed: onPressed,
      mouseCursor: mouseCursor,
      mini: mini,
      shape: shape,
      clipBehavior: clipBehavior,
      focusColor: focusColor,
      hoverColor: hoverColor,
      splashColor: splashColor,
      disabledElevation: disabledElevation,
      focusElevation: focusElevation,
      hoverElevation: hoverElevation,
      highlightElevation: highlightElevation,
      autofocus: autofocus,
      materialTapTargetSize: materialTapTargetSize,
      enableFeedback: enableFeedback,
      tooltip: tooltip,
      foregroundColor: foregroundColor,
      backgroundColor: backgroundColor,
      child: child,
      elevation: elevation,
      focusNode: focusNode,
      heroTag: heroTag,
      isExtended: isExtended,
    );
  }
}
